#!/usr/bin/env python3
"""Add FAQ schema and HTML section to tools that are missing them."""

import re
import os
import subprocess
import sys

TOOLS_DIR = "/Users/mike/zovo-workspaces/zovo-tools"

# FAQ content for each tool (tool_slug -> (title_hint, faqs))
# Each FAQ is (question, answer)
TOOL_FAQS = {
    "529-calculator": [
        ("What is a 529 plan and how does this calculator help?", "A 529 plan is a tax-advantaged savings account designed for education expenses. This calculator helps you project how your contributions will grow over time, factoring in contribution amounts, expected returns, and the number of years until your beneficiary needs the funds."),
        ("Are 529 plan contributions tax-deductible?", "Federal tax deductions are not available for 529 contributions, but over 30 states offer a state income tax deduction or credit for contributions. This calculator focuses on growth projections, so check your state's specific tax benefits separately."),
        ("Can I use 529 funds for expenses other than college tuition?", "Yes. Qualified expenses include tuition, room and board, books, supplies, and computers required for enrollment. Since 2019, you can also use up to $10,000 per year for K-12 tuition and up to $10,000 lifetime to repay student loans."),
        ("What happens if my child does not go to college?", "You can change the beneficiary to another qualifying family member without penalty. Alternatively, since 2024, unused 529 funds can be rolled into a Roth IRA for the beneficiary, subject to certain limits and a 15-year account age requirement."),
        ("How accurate are the projections from this 529 calculator?", "The projections are based on the inputs you provide, including your expected rate of return and contribution schedule. Actual investment performance will vary depending on market conditions and the specific funds in your 529 plan. Use the results as a planning guide rather than a guarantee."),
    ],
    "ai-headshot-generator": [
        ("How does the headshot generator create professional photos?", "The tool uses advanced image processing to enhance your uploaded photo with professional-quality adjustments. It optimizes lighting, background, and framing to produce headshots suitable for LinkedIn, resumes, and corporate profiles."),
        ("What photo format should I upload for the best results?", "For optimal results, upload a high-resolution JPEG or PNG image with good lighting and a clear view of your face. Photos taken in natural light with a simple background tend to produce the most professional-looking headshots."),
        ("Can I use the generated headshot for business purposes?", "Yes. The headshots generated by this tool are yours to use however you choose, including LinkedIn profiles, company websites, email signatures, and printed business materials. There are no usage restrictions on the output images."),
        ("Is my uploaded photo stored or shared anywhere?", "Your photo is processed entirely in your browser and is not uploaded to any server. The tool runs client-side, which means your image never leaves your device, ensuring complete privacy."),
        ("What makes a good professional headshot?", "A strong professional headshot features even lighting, a neutral or lightly blurred background, and a natural expression. The subject should be centered with their eyes roughly in the upper third of the frame. This tool helps achieve these standards automatically."),
    ],
    "ai-image-generator": [
        ("What types of images can this generator create?", "This tool can generate a wide variety of images from text descriptions, including illustrations, concept art, landscapes, portraits, abstract designs, and product mockups. The output quality depends on how specific and descriptive your text prompt is."),
        ("Do I own the images generated by this tool?", "Images generated by this tool are available for your personal and commercial use. However, you should review the specific terms of service for any downstream platform where you plan to publish or sell the images."),
        ("How do I write a good prompt for image generation?", "Be specific about the subject, style, lighting, colors, and composition you want. For example, instead of writing 'a cat,' try 'a tabby cat sitting on a windowsill in warm afternoon sunlight, watercolor style.' More detail generally produces better results."),
        ("What image resolutions are available?", "The tool supports several standard output resolutions suitable for web use, social media, and print. You can select from common aspect ratios including square, landscape, and portrait formats before generating your image."),
        ("Is there a limit to how many images I can generate?", "There is no hard limit on the number of images you can generate in a single session. However, each generation takes a few moments to process, so results are delivered one at a time."),
    ],
    "ama-citation-generator": [
        ("What is AMA citation format?", "AMA (American Medical Association) citation format is a referencing style used primarily in medical and scientific writing. It uses numbered superscript references in the text and lists sources in the order they appear, following specific formatting rules for author names, titles, journal abbreviations, and publication details."),
        ("How do I cite a journal article in AMA format?", "For a journal article, list up to six authors by last name and initials, followed by the article title, abbreviated journal name, year, volume, issue number in parentheses, and page range. This tool automates the formatting so you only need to enter the source details."),
        ("Can this tool generate citations for online sources?", "Yes. The generator supports citations for websites, online journal articles, and other digital resources. It includes fields for URLs and access dates, which are required elements for online sources in AMA format."),
        ("What is the difference between AMA and APA citation styles?", "AMA uses numbered references in order of appearance, while APA uses author-date parenthetical citations arranged alphabetically. AMA is standard in medical journals, whereas APA is common in psychology, education, and social sciences."),
        ("How many authors should I list in an AMA citation?", "List all authors if there are six or fewer. For sources with more than six authors, list the first three followed by 'et al.' This tool handles the formatting automatically based on the number of authors you enter."),
    ],
    "api-request-builder": [
        ("What types of API requests can this tool build?", "This tool supports building GET, POST, PUT, PATCH, and DELETE HTTP requests. You can configure headers, query parameters, request body content, and authentication settings to construct complete API calls ready to execute or copy."),
        ("Can I test my API request directly from this tool?", "Yes. The tool includes a send button that executes your request and displays the response status code, headers, and body. This lets you debug and verify your API endpoints without switching to a separate application."),
        ("What authentication methods does the API builder support?", "The builder supports common authentication methods including Bearer tokens, Basic authentication, and custom header-based auth. You can enter your credentials in the designated fields, and the tool will format the appropriate authorization headers."),
        ("Can I export the generated request as code?", "Yes. The tool can export your configured request as ready-to-use code snippets in multiple languages and formats, including cURL commands, JavaScript fetch, Python requests, and other popular HTTP client formats."),
        ("Is it safe to enter API keys in this tool?", "The tool runs entirely in your browser, and no data is sent to external servers for processing. Your API keys and request data remain on your device. However, the actual API request you send will go to whatever endpoint URL you specify."),
    ],
    "army-body-fat-calculator": [
        ("How does the Army body fat calculator work?", "This calculator uses the U.S. Army body fat measurement method outlined in AR 600-9. It estimates body fat percentage using circumference measurements of the neck, waist, and hips (for women), combined with height. The formula is based on Department of Defense standards."),
        ("What measurements do I need for the Army body fat calculation?", "You need your height, neck circumference, and waist circumference. Women also need to provide hip circumference. All measurements should be taken at the specific anatomical landmarks described in Army Regulation 600-9 for accurate results."),
        ("What are the Army body fat percentage standards?", "Maximum allowable body fat varies by age and gender. For men ages 17-20, the limit is 20%, increasing to 26% for ages 40 and over. For women ages 17-20, the limit is 30%, increasing to 36% for ages 40 and over."),
        ("How accurate is the tape test method compared to other methods?", "The circumference-based tape test has a margin of error of approximately 3-5% compared to methods like DEXA scanning. While not the most precise measurement technique, it is the official standard used by the U.S. Army for body composition assessment."),
        ("Can civilians use this calculator for fitness tracking?", "Absolutely. While this calculator follows Army standards, anyone can use it to estimate body fat percentage. The circumference method provides a reasonable estimate without requiring specialized equipment, making it practical for general fitness monitoring."),
    ],
    "ascii-art-generator": [
        ("What is ASCII art and how does this generator work?", "ASCII art is a graphic design technique that uses printable characters from the ASCII standard to create images and designs. This generator converts your text or images into character-based representations that can be copied and pasted into any text-based medium."),
        ("What types of input does the ASCII art generator accept?", "The generator accepts text input that it converts into large ASCII letter art using various font styles. Some versions also support image uploads, which are converted into character-based representations using different density characters."),
        ("Can I use the generated ASCII art in emails and social media?", "Yes. ASCII art works in any medium that supports plain text, including emails, code comments, terminal applications, text messages, and social media posts. Copy the output directly from the tool and paste it wherever you need it."),
        ("What font styles are available for ASCII text?", "The tool offers multiple font styles including standard block letters, banner text, shadow fonts, and decorative styles. Each font uses different character combinations to create distinct visual effects. Preview each style before copying."),
        ("Why does my ASCII art look distorted when I paste it?", "ASCII art requires a monospaced font to display correctly. If you paste it into an application that uses a proportional font, the characters will not align properly. Use a monospaced font like Courier New, Consolas, or any code editor to preserve the formatting."),
    ],
    "auto-refinance-calculator": [
        ("When does it make sense to refinance a car loan?", "Refinancing typically makes sense when interest rates have dropped since you took out your original loan, your credit score has improved significantly, or you want to change your loan term. This calculator helps you compare your current loan against potential refinance options to see the actual savings."),
        ("How much can I save by refinancing my auto loan?", "Savings depend on the difference between your current interest rate and the new rate, your remaining balance, and the new loan term. This calculator shows you the exact monthly payment change and total interest savings so you can make an informed decision."),
        ("Does refinancing a car loan affect my credit score?", "Applying for refinancing will result in a hard credit inquiry, which may temporarily lower your score by a few points. However, if refinancing leads to lower payments that you manage well, it can improve your credit profile over time. Multiple auto loan inquiries within a 14-day window typically count as a single inquiry."),
        ("What information do I need to use this refinance calculator?", "You need your current loan balance, current interest rate, remaining loan term, and the proposed new interest rate and term. The calculator will compare both scenarios and show you monthly payment differences and total cost savings."),
        ("Can I refinance if I owe more than my car is worth?", "Being underwater on your loan makes refinancing more difficult, as most lenders require the car's value to cover the loan amount. Some lenders offer options for borrowers with negative equity, but the terms are usually less favorable. This calculator helps you evaluate whether the numbers work in your situation."),
    ],
    "baby-name-generator": [
        ("How does the baby name generator suggest names?", "The generator uses a curated database of names filtered by your preferences, including gender, origin, length, and starting letter. It draws from a wide range of cultural traditions and popularity data to provide diverse, meaningful suggestions."),
        ("Can I filter baby names by cultural origin?", "Yes. The tool allows you to filter names by cultural and linguistic origin, including English, Spanish, Hebrew, Arabic, Japanese, Indian, and many other traditions. This helps you find names that reflect your family's heritage or personal preferences."),
        ("Does the generator show name meanings and popularity?", "Each suggested name comes with its meaning, origin, and popularity ranking where available. This context helps you understand the significance behind each name and how common it is in current usage."),
        ("Can I save or compare names from the generator?", "The tool allows you to bookmark favorites and create a shortlist for comparison. This makes it easy to narrow down your options and share your top picks with a partner or family members."),
        ("Are the suggested names appropriate for real children?", "All names in the database are real names used across various cultures worldwide. The tool does not generate fictional or invented names. Each suggestion has genuine cultural roots and documented usage history."),
    ],
    "background-remover": [
        ("How does the background remover process images?", "The tool uses client-side image processing to detect the foreground subject and separate it from the background. It analyzes color contrasts, edges, and shapes to create a clean cutout of your subject with a transparent background."),
        ("What image formats does the background remover support?", "The tool accepts JPEG, PNG, and WebP image uploads. Output is provided as a PNG file with transparency, which preserves the cutout edges and allows you to place the subject on any new background."),
        ("Is my image uploaded to a server for processing?", "No. The background removal happens entirely in your browser using client-side processing. Your images are not uploaded to any external server, ensuring that your photos remain private and secure on your device."),
        ("Can I use the background-removed images for commercial purposes?", "The tool places no restrictions on how you use the output images. You are free to use them for product listings, marketing materials, social media, presentations, or any other commercial or personal purpose."),
        ("What types of backgrounds work best for removal?", "The tool performs best with images that have a clear contrast between the subject and the background. Solid-color backgrounds, studio shots, and well-lit photos produce the cleanest results. Complex backgrounds with colors similar to the subject may require manual touch-up."),
    ],
    "background-remover-tool": [
        ("How is this background remover tool different from other options?", "This tool processes images entirely in your browser without uploading them to any server. It provides instant results with adjustable sensitivity settings, letting you fine-tune the removal threshold for different types of images and backgrounds."),
        ("What resolution images can I process with this tool?", "The tool handles images of various resolutions, though very large files may take longer to process in the browser. For the fastest results, images under 5 megapixels work best while still maintaining sufficient quality for most use cases."),
        ("Can I remove backgrounds from product photos?", "Yes. Product photography is one of the primary use cases for this tool. It works well with product shots taken against solid or semi-solid backgrounds, producing clean cutouts suitable for e-commerce listings and catalog images."),
        ("Does the tool support batch processing of multiple images?", "The tool is designed for processing one image at a time to give you the best control over each result. For multiple images, process each one individually to ensure the removal quality meets your standards."),
        ("How do I get the cleanest edge on my cutout?", "Start with a well-lit photo that has good contrast between the subject and background. Adjust the sensitivity slider to find the sweet spot where the background is fully removed without cutting into your subject. Zoom in to check edge quality before downloading."),
    ],
    "barcode-generator": [
        ("What barcode formats does this generator support?", "The generator supports multiple barcode formats including Code 128, Code 39, EAN-13, EAN-8, UPC-A, ITF-14, and QR codes. Each format serves different purposes, from retail product labeling to inventory management and logistics."),
        ("Can I download the generated barcode as an image file?", "Yes. You can download the barcode in PNG or SVG format. SVG is recommended for print applications because it scales to any size without losing quality, while PNG works well for digital and web use."),
        ("What is the difference between 1D and 2D barcodes?", "One-dimensional barcodes like Code 128 and UPC use parallel lines of varying widths to encode data, typically holding up to 25 characters. Two-dimensional codes like QR codes use a grid pattern and can store much more data, including URLs, contact information, and longer text strings."),
        ("How do I choose the right barcode format for my product?", "The format depends on your use case. UPC-A and EAN-13 are standard for retail products. Code 128 is versatile for shipping labels and inventory. QR codes work best when you need to encode URLs or large amounts of data that will be scanned with a smartphone."),
        ("Will the generated barcodes scan correctly with standard readers?", "Yes. The barcodes generated by this tool conform to industry specifications and will scan correctly with any compatible barcode reader or smartphone scanning app. Always test your barcode with your intended scanning equipment before printing in bulk."),
    ],
    "base64-encoder": [
        ("What is Base64 encoding and when would I use it?", "Base64 is a binary-to-text encoding scheme that converts binary data into a string of ASCII characters. It is commonly used to embed images in HTML or CSS, transmit binary data through text-based protocols like email (MIME), and encode data for URLs and API payloads."),
        ("Does Base64 encoding provide any security or encryption?", "No. Base64 is an encoding scheme, not an encryption method. It transforms data into a different representation but does not protect or secure it. Anyone can decode Base64 text back to its original form. For security, use proper encryption algorithms instead."),
        ("Why does Base64 encoded data appear larger than the original?", "Base64 encoding increases data size by approximately 33%. This is because it represents every three bytes of input as four ASCII characters. While this overhead is acceptable for small data like embedded images, it is worth considering for large files."),
        ("Can I encode files other than text with this tool?", "Yes. This tool can encode any type of data into Base64 format, including text strings, images, documents, and other binary files. Simply paste your text or upload your file, and the tool will produce the Base64-encoded output."),
        ("Is there a size limit for data I can encode?", "The tool handles data encoding in your browser, so the practical limit depends on your device's available memory. For most use cases including text strings and small to medium files, the tool works without any issues. Very large files may be slower to process."),
    ],
    "calorie-deficit-calculator": [
        ("What is a calorie deficit and how does it lead to weight loss?", "A calorie deficit occurs when you consume fewer calories than your body burns in a day. Your body then uses stored fat for energy, resulting in weight loss. This calculator estimates the deficit needed to reach your goal weight within a specified timeframe."),
        ("How does this calculator determine my daily calorie needs?", "The calculator uses the Mifflin-St Jeor equation to estimate your Basal Metabolic Rate (BMR) based on your age, gender, height, and weight. It then multiplies your BMR by an activity factor to determine your Total Daily Energy Expenditure (TDEE), which is the baseline for calculating your deficit."),
        ("What is a safe calorie deficit for sustainable weight loss?", "Most health professionals recommend a deficit of 500 to 750 calories per day, which translates to about 1 to 1.5 pounds of weight loss per week. Deficits larger than 1,000 calories per day are generally not recommended without medical supervision, as they can lead to muscle loss and nutritional deficiencies."),
        ("Does the calculator account for exercise and activity level?", "Yes. You can select your activity level from sedentary to very active, and the calculator adjusts your TDEE accordingly. If you exercise regularly, your calorie needs are higher, which means you can eat more while still maintaining a deficit."),
        ("How accurate is the calorie deficit calculation?", "The calculator provides a well-researched estimate based on established metabolic formulas. Individual results will vary based on factors like metabolism, body composition, genetics, and actual activity levels. Use the results as a starting point and adjust based on your real-world progress over two to four weeks."),
    ],
    "character-counter": [
        ("What does the character counter tool measure?", "This tool counts the total number of characters, words, sentences, and paragraphs in your text. It also tracks character counts with and without spaces, which is useful for meeting specific length requirements on different platforms."),
        ("What character limits do popular social media platforms use?", "Twitter/X allows 280 characters per post. Instagram captions can be up to 2,200 characters. LinkedIn posts support up to 3,000 characters, while LinkedIn articles have no practical limit. Facebook posts allow up to 63,206 characters. This tool helps you stay within these boundaries."),
        ("Does the character counter work with non-English text?", "Yes. The tool correctly counts characters in any language, including those with multi-byte characters like Chinese, Japanese, Korean, and Arabic. Emoji characters are also counted accurately, though some emoji may count as two or more characters depending on the encoding."),
        ("Can I use this tool for SEO meta description length?", "Yes. Google typically displays up to 155-160 characters for meta descriptions and 50-60 characters for title tags. Paste your meta content into this tool to verify it falls within the recommended length before publishing."),
        ("Does the tool count whitespace and special characters?", "Yes. The tool provides separate counts for characters with spaces and characters without spaces. Special characters, punctuation marks, and line breaks are all included in the total character count. This gives you a complete picture of your text's length."),
    ],
    "diff-checker": [
        ("What is a diff checker and how does it work?", "A diff checker compares two blocks of text and highlights the differences between them. It identifies added, removed, and modified lines, making it easy to spot changes between document versions, code revisions, or any two text inputs."),
        ("Can the diff checker compare code files?", "Yes. The tool works with any plain text content, including source code in any programming language. It preserves whitespace and formatting, which is important for languages where indentation is syntactically significant, like Python."),
        ("What diff display modes are available?", "The tool offers side-by-side and unified (inline) diff views. Side-by-side mode shows both texts in parallel columns with changes highlighted. Unified mode shows a single combined view with additions and deletions marked with color coding."),
        ("Does the tool handle large text files?", "The tool processes text comparison in your browser, so it can handle reasonably large documents. For very large files with thousands of lines, processing may take a moment, but it will still produce accurate results without any data being sent to a server."),
        ("Can I ignore whitespace differences in the comparison?", "Yes. The tool includes an option to ignore whitespace changes, which is useful when comparing code that may have different formatting but is functionally identical. This filters out noise from indentation or trailing space differences."),
    ],
    "dns-propagation-checker": [
        ("What is DNS propagation and why does it take time?", "DNS propagation is the process of updating DNS records across all name servers worldwide. When you change DNS settings, those changes need to spread through the global network of DNS servers. This process can take anywhere from a few minutes to 48 hours depending on TTL values and caching."),
        ("How does this tool check DNS propagation status?", "The tool queries multiple DNS servers located in different geographic regions to see if they have received your updated DNS records. By comparing results from servers worldwide, you can see exactly where your changes have propagated and where they are still pending."),
        ("What DNS record types can I check?", "You can check all common DNS record types including A (IPv4 address), AAAA (IPv6 address), CNAME (canonical name), MX (mail exchange), TXT (text records for verification and SPF), NS (name server), and SOA (start of authority) records."),
        ("Why do some servers show my old DNS records while others show the new ones?", "Each DNS server caches records for the duration specified by the TTL (Time To Live) value. Servers that cached your records recently will continue serving the old data until the cache expires. Servers that have not cached your domain or whose cache has expired will fetch and display the new records."),
        ("How can I speed up DNS propagation?", "Lower your TTL value to 300 seconds (5 minutes) at least 24-48 hours before making DNS changes. This ensures caches expire quickly once you update your records. After propagation is complete, you can increase the TTL back to a longer value to reduce query load."),
    ],
    "domain-availability-checker": [
        ("How does the domain availability checker work?", "The tool queries domain registration databases to determine whether a specific domain name is currently registered or available for purchase. It checks in real time and provides immediate results for the domain and extension you specify."),
        ("What domain extensions can I check?", "The tool supports checking availability across popular extensions including .com, .net, .org, .io, .co, .dev, and many other TLDs. You can check multiple extensions simultaneously to find the best available option for your brand or project."),
        ("Why might a domain show as available here but not be purchasable?", "Some domains may be in a redemption period after expiration, reserved by the registry, or held by domain parking services. Additionally, there can be a brief delay between checking availability and completing a purchase, during which someone else may register the domain."),
        ("Can I check bulk domain availability at once?", "The tool is designed for checking individual domain names or a single name across multiple extensions. For bulk availability checking of hundreds of domains, a specialized registrar API would be more appropriate."),
        ("What should I consider when choosing a domain name?", "Keep it short, memorable, and easy to spell. Avoid hyphens and numbers when possible. The .com extension remains the most recognized and trusted, but newer extensions like .io and .dev are well-accepted in the tech industry. Check for trademark conflicts before purchasing."),
    ],
    "fha-loan-calculator": [
        ("What is an FHA loan and who qualifies?", "An FHA loan is a mortgage insured by the Federal Housing Administration, designed for borrowers who may not qualify for conventional loans. You can qualify with a credit score as low as 580 with a 3.5% down payment, or 500 with a 10% down payment. This calculator helps you estimate your monthly payments including mortgage insurance."),
        ("How does FHA mortgage insurance work?", "FHA loans require two types of mortgage insurance: an upfront mortgage insurance premium (UFMIP) of 1.75% of the loan amount, and an annual mortgage insurance premium (MIP) paid monthly. This calculator factors both premiums into your payment estimate so you see the true monthly cost."),
        ("What are the current FHA loan limits?", "FHA loan limits vary by county and are updated annually. In most areas, the standard limit is $498,257 for a single-family home, while high-cost areas can go up to $1,149,825. This calculator allows you to enter any loan amount to estimate your payments."),
        ("How does the FHA calculator differ from a conventional mortgage calculator?", "This calculator includes FHA-specific costs like the upfront mortgage insurance premium and monthly MIP, which conventional loan calculators omit. It also accounts for the lower down payment requirements and specific insurance schedules that apply to FHA loans."),
        ("Can I remove FHA mortgage insurance later?", "For FHA loans originated after June 2013 with less than 10% down, MIP lasts for the life of the loan. The only way to remove it is to refinance into a conventional loan once you have 20% equity. If you put 10% or more down, MIP can be removed after 11 years."),
    ],
    "fraction-calculator": [
        ("What operations can this fraction calculator perform?", "This calculator handles addition, subtraction, multiplication, and division of fractions. It works with proper fractions, improper fractions, and mixed numbers, automatically simplifying results to their lowest terms."),
        ("How does the calculator simplify fractions?", "The calculator finds the greatest common divisor (GCD) of the numerator and denominator, then divides both by that number. This reduces the fraction to its simplest form. For example, 6/8 is simplified to 3/4 by dividing both parts by 2."),
        ("Can I calculate with mixed numbers?", "Yes. Enter mixed numbers using the provided input fields for the whole number, numerator, and denominator. The calculator converts mixed numbers to improper fractions internally for computation, then presents the result as either a simplified fraction or mixed number."),
        ("How do I divide fractions using this tool?", "Select the division operation, enter your two fractions, and the calculator handles the rest. Mathematically, it multiplies the first fraction by the reciprocal of the second. The result is automatically simplified to its lowest terms."),
        ("Does the calculator show the step-by-step solution?", "Yes. The calculator displays each step of the calculation process, including finding common denominators for addition and subtraction, cross-multiplication, and simplification. This makes it a useful learning tool for students studying fractions."),
    ],
    "gradient-generator": [
        ("What types of CSS gradients can this tool create?", "This tool generates linear gradients, radial gradients, and conic gradients. You can set the direction or angle for linear gradients, the shape and position for radial gradients, and the starting angle for conic gradients, all with real-time preview."),
        ("How many color stops can I add to a gradient?", "You can add as many color stops as you need. Each stop includes a color value and an optional position percentage. The tool provides a visual interface for adding, removing, and repositioning stops along the gradient bar."),
        ("Can I copy the CSS code directly from the tool?", "Yes. The tool generates the complete CSS code for your gradient, including vendor prefixes for broader browser compatibility. Click the copy button to place the code on your clipboard, ready to paste into your stylesheet."),
        ("What color formats does the gradient generator support?", "The tool supports HEX, RGB, RGBA, and HSL color formats. You can pick colors using the built-in color picker or enter values directly. RGBA is particularly useful when you want gradient stops with varying transparency levels."),
        ("How do I create a smooth gradient without visible banding?", "Use colors that are relatively close in hue and brightness for the smoothest transitions. Adding intermediate color stops between contrasting colors helps prevent abrupt shifts. For backgrounds, wider gradients across larger elements tend to display smoother than compressed gradients."),
    ],
    "gradient-text-generator": [
        ("How does the gradient text generator apply color to text?", "The tool uses CSS background-clip and text-fill-color properties to apply gradient colors directly to text characters. It generates the necessary CSS code that makes the gradient visible through the text while keeping the background transparent."),
        ("Which browsers support gradient text effects?", "Gradient text is supported in all modern browsers including Chrome, Firefox, Safari, and Edge. The generated CSS includes WebKit prefixes to ensure compatibility with older browser versions. Internet Explorer does not support this effect."),
        ("Can I use the gradient text on my website?", "Yes. Copy the generated CSS code and apply it to any text element on your website. The code is production-ready and works with any HTML text element including headings, paragraphs, and spans. Just add the CSS class to your desired element."),
        ("What happens if a browser does not support gradient text?", "The text will fall back to the standard text color defined in your CSS. The tool generates code that degrades gracefully, meaning users with unsupported browsers will still see readable text, just without the gradient effect."),
        ("Can I animate the gradient on text?", "While this tool generates static gradient text CSS, you can add CSS animations to the generated code to create moving or shifting gradient effects. Common techniques include animating the background-position property to create a flowing color effect across the text."),
    ],
    "hash-generator": [
        ("What hash algorithms does this generator support?", "The tool supports MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashing algorithms. SHA-256 and SHA-512 are recommended for security-sensitive applications, while MD5 is useful for quick checksums and data integrity verification where security is not a concern."),
        ("What is the difference between hashing and encryption?", "Hashing is a one-way function that produces a fixed-length output from any input, and the original data cannot be recovered from the hash. Encryption is a two-way function where data can be decrypted back to its original form using a key. Hashes are used for verification, while encryption is used for confidentiality."),
        ("Can I use this tool to verify file integrity?", "Yes. Generate a hash of your file and compare it to the hash provided by the file's source. If both hashes match exactly, the file has not been altered during transfer. Even a single byte change in the file will produce a completely different hash value."),
        ("Is MD5 still safe to use?", "MD5 is no longer considered secure for cryptographic purposes because collision attacks have been demonstrated. However, it remains useful for non-security applications like checksums, cache keys, and data deduplication where resistance to intentional manipulation is not required."),
        ("Why do different hash algorithms produce different length outputs?", "Each algorithm uses a different internal process and produces a fixed output length specific to that algorithm. MD5 produces a 128-bit (32 character hex) hash, SHA-1 produces 160-bit (40 characters), SHA-256 produces 256-bit (64 characters), and SHA-512 produces 512-bit (128 characters)."),
    ],
    "hourly-wage-calculator": [
        ("How does the hourly wage calculator determine my earnings?", "The calculator multiplies your hourly rate by the number of hours you work per week and the number of weeks you work per year. It accounts for overtime rates, paid time off, and holidays to give you accurate daily, weekly, monthly, and annual income projections."),
        ("Does the calculator account for overtime pay?", "Yes. You can specify the number of overtime hours per week and the overtime rate multiplier (typically 1.5x for time-and-a-half). The calculator separates regular and overtime earnings so you can see exactly how much each contributes to your total income."),
        ("How do I calculate my effective hourly rate from a salary?", "Enter your annual salary and the number of hours you work per week. The calculator divides your annual pay by the total hours worked in a year (weekly hours times 52 weeks) to determine your effective hourly rate, including or excluding vacation time."),
        ("Can I factor in taxes to see my take-home pay?", "The calculator focuses on gross earnings before taxes. Tax withholdings vary significantly based on filing status, deductions, state of residence, and other factors. Use the gross figures from this tool as input for a separate tax calculator to estimate your net pay."),
        ("What is the standard number of work hours in a year?", "A standard full-time work year is 2,080 hours, calculated as 40 hours per week times 52 weeks. After accounting for typical paid holidays (10 days) and vacation (10 days), the actual working hours drop to approximately 1,920 hours. This calculator lets you adjust these values."),
    ],
    "html-encoder": [
        ("What does HTML encoding do to special characters?", "HTML encoding converts special characters into their HTML entity equivalents so they display correctly in web browsers. For example, the less-than sign becomes &lt;, the ampersand becomes &amp;, and quotation marks become &quot;. This prevents browsers from interpreting these characters as HTML markup."),
        ("When should I use HTML encoding?", "Use HTML encoding whenever you need to display code snippets on a web page, include special characters in HTML attributes, or render user-generated content safely. Encoding prevents cross-site scripting (XSS) vulnerabilities by neutralizing potentially malicious HTML and JavaScript in user input."),
        ("What is the difference between HTML encoding and URL encoding?", "HTML encoding converts characters to HTML entities (like &amp; for &) for safe display in web pages. URL encoding converts characters to percent-encoded values (like %20 for space) for safe inclusion in URLs. Each serves a different purpose in web development."),
        ("Does this tool support decoding HTML entities back to characters?", "Yes. The tool works in both directions. You can paste HTML-encoded text to decode it back to its original characters, or paste plain text to encode special characters into their HTML entity form."),
        ("Which characters require HTML encoding?", "The five characters that must always be encoded in HTML are: less-than (<), greater-than (>), ampersand (&), double quote (\"), and single quote ('). Additional characters like non-breaking spaces, copyright symbols, and accented letters can also be encoded for broader compatibility."),
    ],
    "http-status-checker": [
        ("What HTTP status codes does this tool check for?", "The tool reports all standard HTTP status codes returned by a server, including 200 (OK), 301 (Moved Permanently), 302 (Found/Redirect), 403 (Forbidden), 404 (Not Found), 500 (Internal Server Error), and all other codes in the 1xx through 5xx ranges."),
        ("How can I use this tool for SEO auditing?", "Check your important pages to verify they return 200 status codes. Identify 301 and 302 redirects to ensure they point to the correct destinations. Find 404 errors that need fixing and detect any 5xx server errors that could harm your search rankings."),
        ("Does the tool follow redirects?", "Yes. The tool follows the entire redirect chain and shows each hop, including the status code at each step. This is valuable for diagnosing redirect loops, unnecessary redirect chains, and verifying that final destinations are correct."),
        ("Can I check multiple URLs at once?", "Yes. Enter multiple URLs separated by line breaks, and the tool will check each one and display the results in a table format. This makes it efficient to audit batches of pages without checking them individually."),
        ("What does a 503 status code mean for my website?", "A 503 Service Unavailable status means the server is temporarily unable to handle requests, usually due to maintenance or being overloaded. Unlike a 500 error, a 503 signals a temporary condition. Search engines generally treat 503 responses favorably and will retry the page later without penalizing rankings."),
    ],
    "image-cropper": [
        ("What image formats does the cropper support?", "The tool supports JPEG, PNG, WebP, and GIF image formats for input. You can export your cropped image in JPEG or PNG format, with JPEG being best for photographs and PNG for images that require transparency."),
        ("Can I crop to specific aspect ratios?", "Yes. The tool offers preset aspect ratios including 1:1 (square), 4:3, 16:9, 3:2, and custom ratios. You can also enter specific pixel dimensions for the crop area, which is useful when preparing images for platforms with exact size requirements."),
        ("Is the cropping done in my browser?", "Yes. All image processing happens locally in your browser. Your images are never uploaded to any server, ensuring complete privacy. The tool uses the HTML5 Canvas API to perform the crop operation on your device."),
        ("Can I rotate or flip the image before cropping?", "Yes. The tool includes rotation and flip controls that let you adjust the image orientation before defining your crop area. You can rotate in 90-degree increments or use fine rotation for small angle adjustments."),
        ("How do I crop images for social media profile pictures?", "Select the 1:1 square aspect ratio, which is used by most social media platforms for profile pictures. Position the crop area over your subject's face, leaving some space around the head. Most platforms recommend at least 400x400 pixels for profile images."),
    ],
    "inflation-calculator": [
        ("How does the inflation calculator determine purchasing power?", "The calculator uses historical Consumer Price Index (CPI) data published by the Bureau of Labor Statistics to measure how prices have changed between two dates. It shows you what an amount of money in one year would be equivalent to in another year based on actual inflation rates."),
        ("What is the Consumer Price Index and why does it matter?", "The CPI measures the average change in prices paid by consumers for a basket of goods and services over time. It is the most widely used measure of inflation in the United States and directly affects wage negotiations, Social Security adjustments, and financial planning decisions."),
        ("Can I calculate future inflation projections?", "Yes. The tool allows you to project future values using an assumed average inflation rate. While no one can predict exact future inflation, using the historical average of approximately 3% per year provides a reasonable estimate for long-term financial planning."),
        ("How far back does the historical data go?", "The calculator includes CPI data going back to 1913, when the Bureau of Labor Statistics began tracking consumer prices. This gives you over a century of inflation data for comparing purchasing power across different periods in American economic history."),
        ("Why is understanding inflation important for financial planning?", "Inflation erodes the purchasing power of money over time. A dollar today buys less than a dollar did 20 years ago. Understanding inflation helps you set realistic savings goals, evaluate investment returns in real terms, and plan for retirement expenses that will be higher than current costs."),
    ],
    "ip-lookup": [
        ("What information does the IP lookup tool provide?", "The tool provides geolocation data including country, region, city, and approximate coordinates for any IP address. It also shows the Internet Service Provider (ISP), organization name, and autonomous system number (ASN) associated with the address."),
        ("How accurate is the geolocation data?", "IP geolocation is generally accurate to the city level in most developed countries. Country-level accuracy exceeds 99%, while city-level accuracy is typically around 80-90%. The data represents where the IP address is registered, which may differ from the user's physical location if they are using a VPN or proxy."),
        ("Can I look up my own IP address?", "Yes. The tool automatically detects and displays your current public IP address when you first load the page. You can see your own geolocation data, ISP, and other details without entering anything."),
        ("What is the difference between IPv4 and IPv6 addresses?", "IPv4 addresses use a 32-bit format (like 192.168.1.1) with about 4.3 billion possible addresses. IPv6 uses a 128-bit format (like 2001:0db8:85a3::8a2e:0370:7334) with virtually unlimited addresses. This tool supports looking up both formats."),
        ("Is IP lookup legal and ethical?", "Looking up publicly available IP information is legal and a standard practice in network administration, security analysis, and web analytics. The geolocation data is approximate and does not reveal personal identity. It is the same type of information that every website you visit can see."),
    ],
    "json-path-finder": [
        ("What is JSONPath and how does this tool help?", "JSONPath is a query language for navigating and extracting data from JSON documents, similar to XPath for XML. This tool lets you paste a JSON document and visually explore its structure, clicking on any value to see its full JSONPath expression for use in your code."),
        ("What JSONPath syntax does the tool support?", "The tool supports standard JSONPath notation including dot notation ($.store.book), bracket notation ($['store']['book']), array indexing ($[0]), wildcard selectors ($..book), and filter expressions. It generates paths compatible with most JSONPath libraries."),
        ("Can I test JSONPath queries against my data?", "Yes. Enter a JSONPath expression in the query field, and the tool will highlight matching values in your JSON document. This lets you verify that your path selects the correct data before implementing it in your application code."),
        ("Does the tool validate my JSON before parsing?", "Yes. The tool validates your JSON input and displays clear error messages if the format is invalid. It identifies the location of syntax errors, such as missing commas, unclosed brackets, or invalid characters, helping you fix issues before attempting to navigate the structure."),
        ("How does JSONPath handle nested arrays and objects?", "JSONPath uses bracket notation with indices for arrays ($.data[0]) and dot or bracket notation for nested objects ($.data.items or $.data['items']). The recursive descent operator (..) searches all nested levels, making it easy to find values deep within complex structures."),
    ],
    "json-viewer": [
        ("What does the JSON viewer tool do?", "The JSON viewer formats and displays raw JSON data in a readable, color-coded tree structure. It adds proper indentation, syntax highlighting, and collapsible sections, making it easy to explore and understand complex JSON documents."),
        ("Can the JSON viewer handle large files?", "The tool processes JSON in your browser and can handle documents up to several megabytes. For very large files, the initial parsing may take a moment, but once loaded, the collapsible tree view lets you navigate efficiently without scrolling through thousands of lines."),
        ("Does the tool validate JSON input?", "Yes. If your input contains syntax errors, the tool will display a clear error message indicating where the problem is. This makes it useful as a quick JSON validator in addition to a viewer. Valid JSON will render immediately in the formatted tree view."),
        ("Can I search for specific keys or values?", "Yes. The built-in search function lets you filter the tree view by key names or values. Matching nodes are highlighted, and non-matching branches can be collapsed, making it easy to locate specific data points in large documents."),
        ("How is this different from a JSON formatter?", "A JSON formatter primarily reformats text with proper indentation and outputs plain text. This viewer goes further by providing an interactive tree structure with collapsible nodes, syntax highlighting, search capability, and click-to-copy path features for navigating complex data."),
    ],
    "json-yaml-converter": [
        ("What is the difference between JSON and YAML?", "JSON (JavaScript Object Notation) uses braces, brackets, and quotes to structure data. YAML (YAML Ain't Markup Language) uses indentation and minimal punctuation for a more human-readable format. Both represent the same data structures but have different syntax rules and use cases."),
        ("When should I use YAML instead of JSON?", "YAML is preferred for configuration files (like Docker Compose, Kubernetes manifests, and CI/CD pipelines) because it supports comments and is easier to read and edit by hand. JSON is better for data exchange between applications, APIs, and situations where strict parsing is important."),
        ("Does the converter preserve data types during conversion?", "Yes. The tool maintains proper data type mapping between formats. JSON strings, numbers, booleans, arrays, and objects are correctly converted to their YAML equivalents, and vice versa. Null values are also handled properly in both directions."),
        ("Can YAML features like anchors and aliases be converted to JSON?", "YAML anchors and aliases are resolved during conversion, with the referenced data expanded inline in the JSON output. Since JSON does not support references, each occurrence becomes a full copy of the data. Comments in YAML are removed during conversion as JSON does not support them."),
        ("Is there a size limit for conversion?", "The tool processes conversion in your browser, so it can handle files of reasonable size without issues. Documents up to several megabytes convert quickly. Very large files may take longer depending on your device's processing power, but there is no hard limit imposed by the tool."),
    ],
    "json-to-csv-converter": [
        ("How does JSON to CSV conversion work?", "The tool flattens JSON objects into tabular format, using object keys as column headers and values as row data. For arrays of objects with consistent keys, each object becomes a row in the CSV output. Nested objects are flattened using dot notation for column names."),
        ("Can the tool handle nested JSON structures?", "Yes. Nested objects are flattened by concatenating key names with dots (e.g., address.city, address.zip). Nested arrays are serialized as comma-separated values within a single cell or expanded into separate rows, depending on your configuration preferences."),
        ("What happens with inconsistent JSON data?", "If JSON objects in an array have different keys, the tool creates columns for all unique keys found across all objects. Objects missing a particular key will have an empty cell in that column. This ensures no data is lost during conversion."),
        ("Can I choose which fields to include in the CSV?", "Yes. The tool allows you to select specific fields to include or exclude from the CSV output. This is useful when your JSON contains many fields but you only need a subset for your spreadsheet or data analysis."),
        ("Does the converter handle special characters in values?", "Yes. Values containing commas, quotes, or line breaks are automatically enclosed in double quotes following the CSV standard (RFC 4180). Double quotes within values are escaped by doubling them. This ensures the CSV output can be correctly parsed by any spreadsheet application."),
    ],
    "json-to-xml-converter": [
        ("How does JSON to XML conversion handle data types?", "JSON strings, numbers, and booleans are converted to XML text content within named elements. JSON arrays become repeated elements with the same tag name. Null values are represented as empty elements or with a nil attribute, depending on the configuration."),
        ("What root element name does the converter use?", "By default, the tool wraps the output in a root element. You can customize the root element name and configure how array items and object properties are mapped to XML element names. This flexibility lets you match specific XML schema requirements."),
        ("Can the tool generate XML with attributes?", "The standard conversion maps all JSON values to XML elements. Some tools offer a convention where JSON keys starting with '@' are converted to XML attributes. Check the output options to see if attribute mapping is available for your use case."),
        ("Does the converter produce valid, well-formed XML?", "Yes. The output is always well-formed XML with proper encoding declarations, correctly nested elements, and escaped special characters. You can validate the output against any XML parser or schema validator."),
        ("How are JSON arrays converted to XML?", "Each array item becomes a separate XML element. If the array is a value of a key like 'items', each element is typically wrapped in an 'item' child element. The exact naming convention can be configured to match your target XML structure."),
    ],
}

def add_faq_to_tool(tool_slug, faqs):
    """Add FAQ schema and HTML section to a tool's index.html."""
    filepath = os.path.join(TOOLS_DIR, tool_slug, "index.html")

    if not os.path.exists(filepath):
        print(f"  SKIP: {filepath} does not exist")
        return False

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if 'FAQPage' in content:
        print(f"  SKIP: Already has FAQPage schema")
        return False

    # Build FAQ JSON-LD
    faq_entities = []
    for q, a in faqs:
        faq_entities.append(f'{{"@type":"Question","name":"{q}","acceptedAnswer":{{"@type":"Answer","text":"{a}"}}}}')

    faq_jsonld = '<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[' + ','.join(faq_entities) + ']}\n</script>'

    # Build FAQ HTML
    faq_items = []
    for q, a in faqs:
        faq_items.append(f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>')

    faq_html = '<div class="faq-section" style="max-width:800px;margin:2rem auto;padding:0 1rem;"><h2 style="font-size:1.5rem;margin-bottom:1rem;color:#e0e0e8;">Frequently Asked Questions</h2>' + ''.join(faq_items) + '</div>'

    # Insert JSON-LD before </head>
    if '</head>' in content:
        content = content.replace('</head>', faq_jsonld + '</head>', 1)
    else:
        print(f"  ERROR: No </head> tag found")
        return False

    # Insert FAQ HTML before <footer
    if '<footer' in content:
        content = content.replace('<footer', faq_html + '<footer', 1)
    elif '</body>' in content:
        content = content.replace('</body>', faq_html + '</body>', 1)
    else:
        print(f"  WARNING: No footer or body closing tag found, appending before end")
        content = content + faq_html

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return True

def git_commit(tool_slug):
    """Stage and commit changes for a tool."""
    filepath = os.path.join(tool_slug, "index.html")
    subprocess.run(["git", "add", filepath], cwd=TOOLS_DIR, check=True)
    subprocess.run(
        ["git", "commit", "-m", f"Add FAQ schema to {tool_slug}"],
        cwd=TOOLS_DIR, check=True
    )

def main():
    tools = list(TOOL_FAQS.keys())
    commit_count = 0

    for tool_slug in tools:
        faqs = TOOL_FAQS[tool_slug]
        print(f"\nProcessing: {tool_slug}")

        success = add_faq_to_tool(tool_slug, faqs)
        if success:
            git_commit(tool_slug)
            commit_count += 1
            print(f"  DONE: Committed ({commit_count} total)")

            # Push every 20 commits
            if commit_count % 20 == 0:
                print(f"  PUSHING to origin ({commit_count} commits)...")
                subprocess.run(["git", "push", "origin", "main"], cwd=TOOLS_DIR, check=True)
        else:
            print(f"  SKIPPED")

    # Final push if there are remaining commits
    if commit_count > 0 and commit_count % 20 != 0:
        print(f"\n  FINAL PUSH ({commit_count} total commits)...")
        subprocess.run(["git", "push", "origin", "main"], cwd=TOOLS_DIR, check=True)

    print(f"\nComplete! Processed {commit_count} tools.")

if __name__ == "__main__":
    main()
