#!/usr/bin/env python3
"""
Advanced Caching Strategy Implementation
Part of Expansion Agent 4 Technical Optimization Suite
"""

import os
import json
from pathlib import Path
import hashlib
from datetime import datetime, timedelta

class AdvancedCachingSystem:
    def __init__(self, base_path):
        self.base_path = Path(base_path)

    def implement_http_headers_optimization(self, tool_dir):
        """Create optimized .htaccess file for HTTP caching headers"""
        htaccess_content = '''# Advanced HTTP Caching Headers and Performance Optimizations
# Generated by Expansion Agent 4

# Enable compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/plain
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/xml
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE text/javascript
    AddOutputFilterByType DEFLATE application/xml
    AddOutputFilterByType DEFLATE application/xhtml+xml
    AddOutputFilterByType DEFLATE application/rss+xml
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE application/x-javascript
    AddOutputFilterByType DEFLATE application/json
    AddOutputFilterByType DEFLATE application/ld+json
    AddOutputFilterByType DEFLATE font/woff
    AddOutputFilterByType DEFLATE font/woff2
    AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>

# Browser caching with versioning
<IfModule mod_expires.c>
    ExpiresActive On

    # HTML files
    ExpiresByType text/html "access plus 1 hour"

    # CSS and JavaScript
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType text/javascript "access plus 1 year"

    # Images
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/webp "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
    ExpiresByType image/x-icon "access plus 1 year"

    # Fonts
    ExpiresByType font/woff "access plus 1 year"
    ExpiresByType font/woff2 "access plus 1 year"
    ExpiresByType application/font-woff "access plus 1 year"
    ExpiresByType application/font-woff2 "access plus 1 year"

    # JSON and XML
    ExpiresByType application/json "access plus 1 hour"
    ExpiresByType application/xml "access plus 1 hour"

    # Manifest
    ExpiresByType application/manifest+json "access plus 1 week"
</IfModule>

# Cache-Control headers
<IfModule mod_headers.c>
    # HTML files - short cache but allow revalidation
    <FilesMatch "\\.(html|htm)$">
        Header set Cache-Control "max-age=3600, must-revalidate"
        Header set Vary "Accept-Encoding"
    </FilesMatch>

    # CSS and JS - long cache with versioning
    <FilesMatch "\\.(css|js)$">
        Header set Cache-Control "max-age=31536000, immutable"
        Header set Vary "Accept-Encoding"
    </FilesMatch>

    # Images - long cache
    <FilesMatch "\\.(jpg|jpeg|png|gif|webp|svg|ico)$">
        Header set Cache-Control "max-age=31536000, immutable"
    </FilesMatch>

    # Fonts - long cache
    <FilesMatch "\\.(woff|woff2|eot|ttf)$">
        Header set Cache-Control "max-age=31536000, immutable"
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>

    # Service Worker - no cache
    <FilesMatch "service-worker\\.js$">
        Header set Cache-Control "no-cache, no-store, must-revalidate"
        Header set Pragma "no-cache"
        Header set Expires "0"
    </FilesMatch>

    # Security headers
    Header always set X-Content-Type-Options nosniff
    Header always set X-Frame-Options DENY
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"

    # Performance headers
    Header always set Accept-CH "DPR, Viewport-Width, Width"
    Header always set Critical-CH "DPR, Viewport-Width, Width"
</IfModule>

# Enable Keep-Alive
<IfModule mod_headers.c>
    Header set Connection keep-alive
</IfModule>

# Optimize ETags
FileETag None

# Enable HTTP/2 Server Push (if supported)
<IfModule mod_http2.c>
    H2PushPriority * after
    H2PushPriority text/css before
    H2PushPriority text/javascript before
    H2PushPriority font/woff2 interleaved
</IfModule>

# Preload critical resources via Link header
<IfModule mod_headers.c>
    <FilesMatch "\\.html$">
        Header add Link "</css/critical.css>; rel=preload; as=style"
        Header add Link "</js/main.js>; rel=preload; as=script"
        Header add Link "</fonts/main.woff2>; rel=preload; as=font; type=font/woff2; crossorigin"
    </FilesMatch>
</IfModule>

# Content negotiation for WebP
<IfModule mod_rewrite.c>
    RewriteEngine On

    # WebP support detection and serving
    RewriteCond %{HTTP_ACCEPT} image/webp
    RewriteCond %{REQUEST_URI} \\.(jpe?g|png)$
    RewriteCond %{REQUEST_FILENAME}.webp -f
    RewriteRule ^(.*)\\.(jpe?g|png)$ $1.$2.webp [T=image/webp,E=accept:1]

    # Vary header for WebP
    <IfModule mod_headers.c>
        Header append Vary Accept env=REDIRECT_accept
    </IfModule>
</IfModule>

# Minification rules (if mod_pagespeed is available)
<IfModule pagespeed_module>
    ModPagespeed on
    ModPagespeedEnableFilters rewrite_css,rewrite_javascript
    ModPagespeedEnableFilters combine_css,combine_javascript
    ModPagespeedEnableFilters prioritize_critical_css
    ModPagespeedEnableFilters defer_javascript
    ModPagespeedEnableFilters lazyload_images
    ModPagespeedEnableFilters convert_jpeg_to_webp,convert_png_to_webp
    ModPagespeedEnableFilters remove_comments,collapse_whitespace
</IfModule>

# Advanced security and performance
<IfModule mod_rewrite.c>
    # Prevent access to sensitive files
    RewriteRule ^(.*/)?\\.(git|htaccess|htpasswd|env)$ - [F,L]

    # Force HTTPS (uncomment if using SSL)
    # RewriteCond %{HTTPS} off
    # RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>'''

        try:
            htaccess_file = tool_dir / '.htaccess'
            with open(htaccess_file, 'w', encoding='utf-8') as f:
                f.write(htaccess_content)
            return True
        except Exception as e:
            print(f"Error creating .htaccess for {tool_dir}: {e}")
            return False

    def create_advanced_service_worker(self, tool_dir, tool_name):
        """Create advanced service worker with intelligent caching strategies"""
        sw_content = f'''// Advanced Service Worker v4.0 - {tool_name}
// Intelligent caching with network-first, cache-first, and stale-while-revalidate strategies

const CACHE_VERSION = '4.0.{int(datetime.now().timestamp())}';
const CACHE_PREFIX = 'zovo-{tool_name.replace("-", "")}';
const STATIC_CACHE = CACHE_PREFIX + '-static-' + CACHE_VERSION;
const DYNAMIC_CACHE = CACHE_PREFIX + '-dynamic-' + CACHE_VERSION;
const IMAGE_CACHE = CACHE_PREFIX + '-images-' + CACHE_VERSION;
const API_CACHE = CACHE_PREFIX + '-api-' + CACHE_VERSION;

// Cache duration in milliseconds
const CACHE_DURATIONS = {{
  static: 30 * 24 * 60 * 60 * 1000,    // 30 days
  dynamic: 7 * 24 * 60 * 60 * 1000,    // 7 days
  images: 60 * 24 * 60 * 60 * 1000,    // 60 days
  api: 60 * 60 * 1000                  // 1 hour
}};

// Static assets to precache
const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  '/css/main.css',
  '/js/main.js',
  '/icons/icon-192x192.png',
  '/icons/icon-512x512.png'
];

// API endpoints to cache
const CACHEABLE_APIS = [
  '/api/calculate',
  '/api/rates',
  '/api/data'
];

// Install event - aggressive precaching
self.addEventListener('install', event => {{
  console.log('[SW] Installing service worker for {tool_name}');

  event.waitUntil(
    Promise.all([
      // Cache static assets
      caches.open(STATIC_CACHE).then(cache => {{
        console.log('[SW] Precaching static assets');
        return cache.addAll(STATIC_ASSETS.map(url => new Request(url, {{ cache: 'reload' }})));
      }}),

      // Initialize other caches
      caches.open(DYNAMIC_CACHE),
      caches.open(IMAGE_CACHE),
      caches.open(API_CACHE)
    ]).then(() => {{
      console.log('[SW] Installation complete');
      return self.skipWaiting();
    }}).catch(error => {{
      console.error('[SW] Installation failed:', error);
    }})
  );
}});

// Activate event - cleanup old caches
self.addEventListener('activate', event => {{
  console.log('[SW] Activating service worker');

  event.waitUntil(
    Promise.all([
      // Clean up old caches
      caches.keys().then(cacheNames => {{
        return Promise.all(
          cacheNames
            .filter(name => name.startsWith(CACHE_PREFIX) &&
                           !name.includes(CACHE_VERSION))
            .map(name => {{
              console.log('[SW] Deleting old cache:', name);
              return caches.delete(name);
            }})
        );
      }}),

      // Claim all clients
      self.clients.claim()
    ]).then(() => {{
      console.log('[SW] Activation complete');
    }})
  );
}});

// Fetch event - intelligent caching strategies
self.addEventListener('fetch', event => {{
  const request = event.request;
  const url = new URL(request.url);

  // Skip non-GET requests
  if (request.method !== 'GET') {{
    return;
  }}

  // Skip chrome-extension requests
  if (url.protocol === 'chrome-extension:') {{
    return;
  }}

  // Route requests to appropriate cache strategies
  if (isStaticAsset(url)) {{
    event.respondWith(handleStaticAsset(request));
  }} else if (isImage(url)) {{
    event.respondWith(handleImage(request));
  }} else if (isAPI(url)) {{
    event.respondWith(handleAPI(request));
  }} else {{
    event.respondWith(handleDynamic(request));
  }}
}});

// Static asset strategy: Cache First with background update
async function handleStaticAsset(request) {{
  try {{
    const cache = await caches.open(STATIC_CACHE);
    const cachedResponse = await cache.match(request);

    if (cachedResponse && !isExpired(cachedResponse, CACHE_DURATIONS.static)) {{
      // Serve from cache and update in background
      updateCache(request, cache);
      return cachedResponse;
    }}

    // Fetch from network and cache
    const networkResponse = await fetch(request);
    if (networkResponse.status === 200) {{
      await cache.put(request, networkResponse.clone());
    }}
    return networkResponse;

  }} catch (error) {{
    console.error('[SW] Static asset error:', error);
    // Try to serve from cache as fallback
    const cache = await caches.open(STATIC_CACHE);
    return await cache.match(request) || new Response('Offline', {{ status: 503 }});
  }}
}}

// Image strategy: Cache First with WebP conversion
async function handleImage(request) {{
  try {{
    const cache = await caches.open(IMAGE_CACHE);
    const cachedResponse = await cache.match(request);

    if (cachedResponse && !isExpired(cachedResponse, CACHE_DURATIONS.images)) {{
      return cachedResponse;
    }}

    // Try WebP version first if supported
    const supportsWebP = request.headers.get('Accept')?.includes('image/webp');
    if (supportsWebP && !request.url.includes('.webp')) {{
      const webpUrl = request.url.replace(/\\.(jpg|jpeg|png)$/i, '.webp');
      try {{
        const webpResponse = await fetch(webpUrl);
        if (webpResponse.status === 200) {{
          await cache.put(request, webpResponse.clone());
          return webpResponse;
        }}
      }} catch (e) {{
        // WebP not available, continue with original
      }}
    }}

    const networkResponse = await fetch(request);
    if (networkResponse.status === 200) {{
      await cache.put(request, networkResponse.clone());
    }}
    return networkResponse;

  }} catch (error) {{
    console.error('[SW] Image error:', error);
    return new Response('Image not available offline', {{ status: 503 }});
  }}
}}

// API strategy: Network First with Stale While Revalidate
async function handleAPI(request) {{
  try {{
    const cache = await caches.open(API_CACHE);

    // Try network first
    const networkResponse = await fetch(request, {{ timeout: 3000 }});
    if (networkResponse.status === 200) {{
      await cache.put(request, networkResponse.clone());
      return networkResponse;
    }}

    // Fall back to cache
    const cachedResponse = await cache.match(request);
    return cachedResponse || new Response('API unavailable', {{ status: 503 }});

  }} catch (error) {{
    console.error('[SW] API error:', error);
    // Serve from cache
    const cache = await caches.open(API_CACHE);
    const cachedResponse = await cache.match(request);
    return cachedResponse || new Response(
      JSON.stringify({{ error: 'Offline', cached: false }}),
      {{ headers: {{ 'Content-Type': 'application/json' }}, status: 503 }}
    );
  }}
}}

// Dynamic content strategy: Stale While Revalidate
async function handleDynamic(request) {{
  try {{
    const cache = await caches.open(DYNAMIC_CACHE);
    const cachedResponse = await cache.match(request);

    // Serve cached version immediately if available
    if (cachedResponse) {{
      // Update cache in background
      fetch(request).then(response => {{
        if (response.status === 200) {{
          cache.put(request, response);
        }}
      }}).catch(e => console.log('[SW] Background update failed:', e));

      return cachedResponse;
    }}

    // No cache, fetch from network
    const networkResponse = await fetch(request);
    if (networkResponse.status === 200) {{
      await cache.put(request, networkResponse.clone());
    }}
    return networkResponse;

  }} catch (error) {{
    console.error('[SW] Dynamic content error:', error);
    return new Response('Content unavailable offline', {{ status: 503 }});
  }}
}}

// Utility functions
function isStaticAsset(url) {{
  return url.pathname.match(/\\.(css|js|woff2?|eot|ttf)$/) ||
         url.pathname === '/' ||
         url.pathname.endsWith('.html') ||
         url.pathname.includes('/manifest.json');
}}

function isImage(url) {{
  return url.pathname.match(/\\.(jpg|jpeg|png|gif|webp|svg|ico)$/);
}}

function isAPI(url) {{
  return CACHEABLE_APIS.some(api => url.pathname.startsWith(api)) ||
         url.pathname.startsWith('/api/');
}}

function isExpired(response, maxAge) {{
  const dateHeader = response.headers.get('date');
  if (!dateHeader) return true;

  const responseTime = new Date(dateHeader).getTime();
  return (Date.now() - responseTime) > maxAge;
}}

async function updateCache(request, cache) {{
  try {{
    const response = await fetch(request);
    if (response.status === 200) {{
      await cache.put(request, response);
    }}
  }} catch (e) {{
    console.log('[SW] Background update failed:', e);
  }}
}}

// Background sync for analytics and offline data
self.addEventListener('sync', event => {{
  if (event.tag === 'analytics-sync') {{
    event.waitUntil(syncAnalytics());
  }} else if (event.tag === 'calculation-sync') {{
    event.waitUntil(syncCalculations());
  }}
}});

async function syncAnalytics() {{
  try {{
    const analyticsData = await getStoredData('analytics-queue');
    for (const data of analyticsData) {{
      await fetch('/api/analytics', {{
        method: 'POST',
        body: JSON.stringify(data),
        headers: {{ 'Content-Type': 'application/json' }}
      }});
    }}
    await clearStoredData('analytics-queue');
  }} catch (error) {{
    console.error('[SW] Analytics sync failed:', error);
  }}
}}

async function syncCalculations() {{
  try {{
    const calculations = await getStoredData('calculation-queue');
    for (const calc of calculations) {{
      await fetch('/api/calculations', {{
        method: 'POST',
        body: JSON.stringify(calc),
        headers: {{ 'Content-Type': 'application/json' }}
      }});
    }}
    await clearStoredData('calculation-queue');
  }} catch (error) {{
    console.error('[SW] Calculation sync failed:', error);
  }}
}}

// IndexedDB utilities for offline storage
async function getStoredData(key) {{
  return new Promise((resolve, reject) => {{
    const request = indexedDB.open('ZovoOfflineDB', 1);
    request.onsuccess = () => {{
      const db = request.result;
      const transaction = db.transaction(['data'], 'readonly');
      const store = transaction.objectStore('data');
      const getRequest = store.get(key);

      getRequest.onsuccess = () => {{
        resolve(getRequest.result?.data || []);
      }};
      getRequest.onerror = () => reject(getRequest.error);
    }};
    request.onerror = () => reject(request.error);
  }});
}}

async function clearStoredData(key) {{
  return new Promise((resolve, reject) => {{
    const request = indexedDB.open('ZovoOfflineDB', 1);
    request.onsuccess = () => {{
      const db = request.result;
      const transaction = db.transaction(['data'], 'readwrite');
      const store = transaction.objectStore('data');
      const deleteRequest = store.delete(key);

      deleteRequest.onsuccess = () => resolve();
      deleteRequest.onerror = () => reject(deleteRequest.error);
    }};
    request.onerror = () => reject(request.error);
  }});
}}

// Push notification handling
self.addEventListener('push', event => {{
  if (event.data) {{
    const data = event.data.json();
    const options = {{
      body: data.body,
      icon: '/icons/icon-192x192.png',
      badge: '/icons/badge-72x72.png',
      vibrate: [100, 50, 100],
      data: data.data,
      actions: [
        {{
          action: 'open',
          title: 'Open Calculator',
          icon: '/icons/open.png'
        }},
        {{
          action: 'dismiss',
          title: 'Dismiss',
          icon: '/icons/dismiss.png'
        }}
      ]
    }};

    event.waitUntil(
      self.registration.showNotification(data.title, options)
    );
  }}
}});

// Notification click handling
self.addEventListener('notificationclick', event => {{
  event.notification.close();

  if (event.action === 'open') {{
    event.waitUntil(
      clients.openWindow('/')
    );
  }}
}});

console.log('[SW] Advanced service worker for {tool_name} loaded successfully');'''

        try:
            sw_file = tool_dir / 'sw-advanced.js'
            with open(sw_file, 'w', encoding='utf-8') as f:
                f.write(sw_content)
            return True
        except Exception as e:
            print(f"Error creating advanced service worker for {tool_dir}: {e}")
            return False

    def create_cache_manifest(self, tool_dir):
        """Create cache manifest for offline functionality"""
        manifest_content = '''CACHE MANIFEST
# Advanced Cache Manifest v4.0
# Generated: ''' + datetime.now().isoformat() + '''

CACHE:
# Core files
/
/index.html
/manifest.json
/sw-advanced.js

# Stylesheets
/css/main.css
/css/critical.css

# JavaScript
/js/main.js
/js/calculator.js
/js/performance.js

# Images
/icons/icon-72x72.png
/icons/icon-192x192.png
/icons/icon-512x512.png
/images/logo.png
/images/hero.webp

# Fonts
/fonts/main.woff2
/fonts/main.woff

NETWORK:
# Always fetch from network
/api/*
/analytics/*
*

FALLBACK:
# Offline fallbacks
/api/ /offline/api.json
/images/ /offline/placeholder.png
/ /offline.html'''

        try:
            manifest_file = tool_dir / 'cache.manifest'
            with open(manifest_file, 'w', encoding='utf-8') as f:
                f.write(manifest_content)
            return True
        except Exception as e:
            print(f"Error creating cache manifest for {tool_dir}: {e}")
            return False

    def optimize_all_s_w_tools(self):
        """Apply advanced caching to all S-W tools"""
        tools = []
        for path in self.base_path.iterdir():
            if path.is_dir() and not path.name.startswith('.'):
                first_letter = path.name[0].lower()
                if 's' <= first_letter <= 'w':
                    tools.append(path)

        optimized_count = 0

        for tool_dir in tools[:20]:  # Process 20 more tools
            tool_name = tool_dir.name
            print(f"📦 Adding advanced caching to {tool_name}...")

            optimizations = 0

            if self.implement_http_headers_optimization(tool_dir):
                optimizations += 1
                print(f"   ✅ HTTP headers optimization")

            if self.create_advanced_service_worker(tool_dir, tool_name):
                optimizations += 1
                print(f"   ✅ Advanced service worker")

            if self.create_cache_manifest(tool_dir):
                optimizations += 1
                print(f"   ✅ Cache manifest")

            if optimizations > 0:
                optimized_count += 1

        return optimized_count, len(tools[:20])

def main():
    print("💾 ADVANCED CACHING SYSTEM IMPLEMENTATION")
    print("=" * 60)

    caching_system = AdvancedCachingSystem('/Users/mike/zovo-workspaces/zovo-tools')
    optimized, total = caching_system.optimize_all_s_w_tools()

    print(f"\\n🎯 CACHING OPTIMIZATION SUMMARY")
    print(f"Tools processed: {total}")
    print(f"Tools optimized: {optimized}")
    print(f"Advanced caching strategies implemented!")

if __name__ == "__main__":
    main()