#!/bin/bash
# Advanced Image Optimization Script
# Generated by Expansion Agent 4

# Create directories if they don't exist
mkdir -p images/optimized
mkdir -p images/webp
mkdir -p images/avif

# Function to optimize images
optimize_image() {
    local input=$1
    local filename=$(basename "$input")
    local name="${filename%.*}"
    local ext="${filename##*.}"

    echo "Optimizing $filename..."

    # Create WebP version
    if command -v cwebp &> /dev/null; then
        cwebp -quality 85 -m 6 "$input" -o "images/webp/${name}.webp"
        echo "  ✅ WebP version created"
    fi

    # Create AVIF version (next-gen format)
    if command -v avifenc &> /dev/null; then
        avifenc --min 20 --max 40 --speed 6 "$input" "images/avif/${name}.avif"
        echo "  ✅ AVIF version created"
    fi

    # Optimize original
    case $ext in
        jpg|jpeg)
            if command -v jpegoptim &> /dev/null; then
                jpegoptim --max=85 --strip-all --all-progressive "$input"
                echo "  ✅ JPEG optimized"
            fi
            ;;
        png)
            if command -v optipng &> /dev/null; then
                optipng -o7 "$input"
                echo "  ✅ PNG optimized"
            fi
            if command -v pngcrush &> /dev/null; then
                pngcrush -rem alla -brute "$input" "images/optimized/${filename}"
                echo "  ✅ PNG crushed"
            fi
            ;;
        svg)
            if command -v svgo &> /dev/null; then
                svgo --multipass "$input"
                echo "  ✅ SVG optimized"
            fi
            ;;
    esac
}

# Find and optimize all images
find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.svg" \) -not -path "./images/optimized/*" -not -path "./images/webp/*" -not -path "./images/avif/*" | while read image; do
    optimize_image "$image"
done

echo "🎉 Image optimization complete!"
